src/Entity/Header.php
<?php

namespace App\Entity;

use App\Repository\HeaderRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

#[ORM\Entity(repositoryClass: HeaderRepository::class)]
#[Vich\Uploadable]
class Header
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Heading = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image = null;

    #[Vich\UploadableField(mapping: 'header_image', fileNameProperty: 'image')]
    private ?File $imageFile = null;

    #[ORM\OneToOne()]
    private ?Quiz $quiz = null;

    private const DEFAULT_IMAGE = 'quiz.png';

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getHeading(): ?string
    {
        return $this->Heading;
    }

    public function setHeading(string $Heading): static
    {
        $this->Heading = $Heading;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImage(?string $image): void
    {
        $this->image = $image;
    }

    public function getImage(): ?string
    {
        return $this->image ?: self::DEFAULT_IMAGE;
    }

    public function getQuiz(): ?Quiz
    {
        return $this->quiz;
    }

    public function setQuiz(?Quiz $quiz): static
    {
        $this->quiz = $quiz;

        return $this;
    }
}

src/Entity/Questions.php
<?php

namespace App\Entity;

use App\Repository\QuestionsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: QuestionsRepository::class)]
class Questions
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $question = null;

    #[ORM\OneToMany(targetEntity: Answers::class, mappedBy: 'question', orphanRemoval: true, cascade: ['persist', 'remove'])]
    private Collection $answers;

    #[ORM\Column]
    private ?int $rank = null;

    #[ORM\ManyToOne(inversedBy: 'question')]
    private ?Quiz $quiz = null;

    public function __construct()
    {
        $this->answers = new ArrayCollection();
    }


    public function __ToString()
    {
        return($this->question);
    }
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getQuestion(): ?string
    {
        return $this->question;
    }

    public function setQuestion(string $question): static
    {
        $this->question = $question;

        return $this;
    }

    /**
     * @return Collection<int, Answers>
     */
    public function getAnswers(): Collection
    {
        return $this->answers;
    }

    public function addAnswer(Answers $answer): static
    {
        if (!$this->answers->contains($answer)) {
            $this->answers->add($answer);
            $answer->setQuestion($this);
        }

        return $this;
    }

    public function removeAnswer(Answers $answer): static
    {
        if ($this->answers->removeElement($answer)) {
            // set the owning side to null (unless already changed)
            if ($answer->getQuestion() === $this) {
                $answer->setQuestion(null);
            }
        }

        return $this;
    }

    public function getRank(): ?int
    {
        return $this->rank;
    }

    public function setRank(int $rank): static
    {
        $this->rank = $rank;

        return $this;
    }

    public function getQuiz(): ?Quiz
    {
        return $this->quiz;
    }

    public function setQuiz(?Quiz $quiz): static
    {
        $this->quiz = $quiz;

        return $this;
    }
}

src/Controller/QuestionsController.php
<?php

namespace App\Controller;

use App\Repository\HeaderRepository;
use App\Repository\QuestionsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class QuestionsController extends AbstractController
{
    #[Route('/', name: 'app_questions')]
    public function index(QuestionsRepository $questionsRepository,HeaderRepository $headerRepository): Response
    {
        $questions = $questionsRepository->findAllWithAnswers();
        $header = $headerRepository->createQueryBuilder('h')
            ->setFirstResult(0)
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();


        return $this->render('questions/index.html.twig', [
            'questions' => $questions,
            'header' =>$header
            ]);
    }
}

templates/questions/index-two.html.twig
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Freeman&family=Jost:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">

    {% if header.image is defined %}
        <link type="image/png" href="/images/headers/{{ header.image }}" rel="icon" sizes="128x128">
        <link type="image/png" href="/images/headers/{{ header.image }}" rel="icon" sizes="64x64">
        <link type="image/png" href="/images/headers/{{ header.image }}" rel="icon" sizes="32x32">
    {% endif %}
    {% if header.heading is defined %}
        <title>{{ header.heading }}</title>
    {% endif %}
    <meta name="description" content="Early signs and symptoms of prostate cancer for early detection. Understand risk factors and when to seek medical advice for better outcomes.">

    <link rel="preload" as="style" href="{{ asset('/build/assets/app-OU6soXXO.css') }}">
    <link rel="modulepreload" href="{{ asset('/build/assets/app-DkDdL2UM.js') }}">
    <link rel="stylesheet" href="{{ asset('/build/assets/app-OU6soXXO.css') }}" data-navigate-track="reload">
    <script type="module" src="{{ asset('/build/assets/app-DkDdL2UM.js') }}" data-navigate-track="reload"></script>

    <style>
        .selected{
            display: inline-block !important;
            background-color: #FFC107 !important;
            color: #212121 !important;
            font-family: 'Montserrat', sans-serif !important;
            font-size: 1.125rem !important;
            font-weight: 700 !important;
            text-decoration: none !important;
            border-radius: 4px !important;
        }
        .button {
            display: inline-block;
            background-color: #FFC107;
            color: #212121;
            font-family: 'Montserrat', sans-serif;
            font-size: 1.125rem;
            font-weight: 700;
            padding: 12px 24px;
            text-decoration: none;
            border-radius: 4px;
            margin-top: 20px;
        }
        body {
            font-family: 'Jost', sans-serif;
        }
        .container {
            width: 80%;
            margin: 0 auto;
        }
        .question {
            display: none;
        }
        .question.active {
            display: block;
        }
        .bg-white {
            background-color: white;
        }
        .text-neutral-700 {
            color: #1E88E5;
            font-family: 'Montserrat', sans-serif;

        }
        .text-neutral-400 {
            color: #b0b0b0;
        }
        .text-md {
            font-size: 1rem;
        }
        .text-sm {
            font-size: 0.875rem;
        }
        .text-base {
            font-size: 1rem;
        }
        .font-bold {
            font-weight: bold;
        }
        .font-medium {
            font-weight: 500;
        }
        .bg-neutral-100 {
            background-color: #f5f5f5;
        }
        .bg-indigo-600 {
            background-color: #FFC107 !important;
            color: #212121 !important;


        }
        .text-white {
            color: white;
        }
        .rounded-md {
            border-radius: 0.375rem;
        }
        .p-8 {
            padding: 2rem;
        }
        .p-4 {
            padding: 1rem;
        }
        .transition {
            transition: all 0.15s ease-in-out;
        }
        .hover\:bg-neutral-200:hover {
            background-color: #e5e5e5;
        }
        .hover\:bg-indigo-700:hover {
            background-color: #434190;
        }
        .cursor-not-allowed {
            cursor: not-allowed;
        }
        .space-y-2 > :not(:last-child) {
            margin-bottom: 0.5rem;
        }
        .space-y-6 > :not(:last-child) {
            margin-bottom: 1.5rem;
        }
        .space-x-4 > :not(:last-child) {
            margin-right: 1rem;
        }
        .w-full {
            width: 100%;
        }
        .h-full {
            height: 100%;
        }
        .min-h-[calc(100vh-128px)] {
            min-height: calc(100vh - 128px);
        }
        .flex {
            display: flex;
        }
        .flex-col {
            flex-direction: column;
        }
        .items-center {
            align-items: center;
        }
        .justify-center {
            justify-content: center;
        }
        .justify-between {
            justify-content: space-between;
        }
        .rounded-lg {
            border-radius: 0.5rem;
        }
        .border {
            border-width: 1px;
        }
        .border-neutral-300 {
            border-color: #d4d4d4;
        }
        .bg-neutral-200 {
            background-color: #e5e5e5;
        }
        .bg-indigo-600 {
            background-color: #4c51bf;
        }
        .overflow-hidden {
            overflow: hidden;
        }
        .selected {
            background-color: #4c51bf;
            color: white;
        }
    </style>
</head>
<body>
<header class="bg-white">
    <div class="flex justify-center items-center container h-32">
        <div class="flex items-center flex-row desktop:space-x-6 tablet:space-x-4 mobile:space-x-3">
            {% if header.image is defined %}
                <img class="w-16 h-16 mobile:w-12 mobile:h-12" src="/images/headers/{{ header.image }}" alt="image">
            {% endif %}
            <div class="flex flex-col space-y-1">
                {% if header.heading is defined %}
                    <h1 class="desktop:text-2xl text-base font-bold text-neutral-700">{{ header.heading }}</h1>
                {% endif %}
                {% if header.description is defined %}
                    <p class="desktop:text-base mobile:text-sm font-medium text-neutral-400">{{ header.description }}</p>
                {% endif %}
            </div>
        </div>
    </div>
</header>
<main class="flex justify-center items-start container min-h-[calc(100vh-128px)]">
    <div class="flex-grow desktop:my-10 tablet:my-8 mobile:my-6">
        <div class="flex flex-col space-y-6">
            <div id="question-{{ question.id }}" class="question active" data-selected="false">
                <div class="bg-white rounded-lg p-8 flex flex-col space-y-6 w-full">
                    <p {% if question.quiz.name == "fitai" %} style="direction: rtl" {% endif %}class="text-2xl font-semibold text-neutral-700">{{ question.rank }}. {{ question.question }}</p>
                    <div class="flex flex-col space-y-2">
                        {% for answer in question.answers %}
                            <button class="bg-neutral-100 text-neutral-500 font-medium hover:bg-neutral-200 justify-center px-6 py-4 text-sm flex items-center rounded-md transition duration-150 ease-in-out" onclick="selectAnswer(this, {{ question.id }})">{{ answer.answer }}</button>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="flex justify-between items-center">
                {% if isFirstQuestion %}
                    <a href="/{{ name }}">
                        <button class="bg-neutral-100 text-neutral-500 font-medium hover:bg-neutral-200 px-6 py-4 text-sm rounded-md transition duration-150 ease-in-out">
                            Previous
                        </button>
                    </a>
                {% else %}
                    {% if question.id > 1 %}
                        <a href="{{ path('app_quiz_question', { 'name': question.quiz.name, 'questionId': question.id - 1 }) }}" class="bg-neutral-100 text-neutral-500 font-medium hover:bg-neutral-200 px-6 py-4 text-sm rounded-md transition duration-150 ease-in-out">Previous</a>
                    {% endif %}
                {% endif %}
                {% if nextQuestionId is not null %}
                    <a href="{{ path('app_quiz_question', { 'name': question.quiz.name, 'questionId': nextQuestionId }) }}" class="next-question bg-indigo-600 text-white font-medium hover:bg-indigo-700 px-6 py-4 text-sm rounded-md transition duration-150 ease-in-out">Next</a>
                {% else %}

                    <a href="{{ path('app_result',{ 'name': question.quiz.name }) }}" class="next-question bg-indigo-600 text-white font-medium hover:bg-indigo-700 px-6 py-4 text-sm rounded-md transition duration-150 ease-in-out">Next</a>
                {% endif %}
            </div>
        </div>
    </div>
</main>
<footer class="flex justify-center items-center h-32 bg-white">
    <p class="text-sm font-medium text-neutral-400">© 2024 Your Company. All rights reserved.</p>
</footer>
<script>
    function selectAnswer(button, questionId) {
        // Deselect all buttons for the current question
        const buttons = button.parentElement.getElementsByTagName('button');
        for (let btn of buttons) {
            btn.classList.remove('selected');
        }

        // Select the clicked button
        button.classList.add('selected');

        // Store the answer
        localStorage.setItem(`question-${questionId}`, button.innerText);

        // Mark the question as having a selected answer
        document.getElementById(`question-${questionId}`).dataset.selected = "true";
    }

    document.addEventListener('DOMContentLoaded', () => {
        // Restore the selected answer if it exists
        const questionId = {{ question.id }};
        const selectedAnswer = localStorage.getItem(`question-${questionId}`);
        if (selectedAnswer) {
            const buttons = document.getElementById(`question-${questionId}`).getElementsByTagName('button');
            for (let btn of buttons) {
                if (btn.innerText === selectedAnswer) {
                    btn.classList.add('selected');
                    document.getElementById(`question-${questionId}`).dataset.selected = "true";
                    break;
                }
            }
        }

        // Add event listeners to next buttons
        const nextButtons = document.querySelectorAll('.next-question');
        nextButtons.forEach(button => {
            button.addEventListener('click', function(event) {
                const questionElement = document.getElementById(`question-${questionId}`);
                if (questionElement.dataset.selected !== "true") {
                    event.preventDefault();
                    alert("Please select an answer before proceeding to the next question.");
                }
            });
        });
    });
</script>

<script>
    async function fetchUtms() {
        try {
            const response = await fetch('http://localhost:8000/api/fraud');
            const data = await response.json();
            return data.frauds.map(fraud => fraud.word);
        } catch (error) {
            console.error('Error fetching UTMs:', error);
            return [];
        }
    }

    async function isUtms() {
        const utms = await fetchUtms();
        const url = new URL(window.location.href);

        const params = new URLSearchParams(url.search);

        const utm = params.get('utm_source');

        return utms.includes(utm);
    }

    function loadGptScript() {
        var script = document.createElement('script');

        script.async = true;

        script.src = "https://securepubads.g.doubleclick.net/tag/js/gpt.js";

        document.head.appendChild(script);

        console.log('ad loaded');
    }

    function fraudCheck(callback) {
        window.kmnr = {
            kmnrKey: '376749059',
            sub1: location.hostname,
            sub2: '',
            sub3: '',
        };

        var kmnrSc = document.createElement('script');
        var kmnrPrnt = document.getElementsByTagName('head')[0] || document.body;
        kmnrSc.setAttribute('async', true);
        kmnrSc.setAttribute('charset', 'utf-8');
        kmnrSc.src = '//kaminari.systems/v1/script.js?kmnrKey=' + window.kmnr.kmnrKey;
        kmnrPrnt && kmnrPrnt.appendChild(kmnrSc);

        setTimeout(callback, 1500);
    }

    if (isUtms()) {
        fraudCheck(loadGptScript);
    } else {
        loadGptScript();
    }
</script>
</body>
</html>

templates/questions/index.html.twig
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Freeman&family=Jost:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">

    {% if header.image is defined %}
        <link type="image/png" href="/images/headers/{{ header.image }}" rel="icon" sizes="128x128">
        <link type="image/png" href="/images/headers/{{ header.image }}" rel="icon" sizes="64x64">
        <link type="image/png" href="/images/headers/{{ header.image }}" rel="icon" sizes="32x32">
    {% endif %}
    {% if header.heading is defined %}
        <title>{{ header.heading }}</title>
    {% endif %}
    <meta name="description" content="Early signs and symptoms of prostate cancer for early detection. Understand risk factors and when to seek medical advice for better outcomes.">

    <link rel="preload" as="style" href="{{ asset('/build/assets/app-OU6soXXO.css') }}">
    <link rel="modulepreload" href="{{ asset('/build/assets/app-DkDdL2UM.js') }}">
    <link rel="stylesheet" href="{{ asset('/build/assets/app-OU6soXXO.css') }}" data-navigate-track="reload">
    <script type="module" src="{{ asset('/build/assets/app-DkDdL2UM.js') }}" data-navigate-track="reload"></script>

    <style>
        body {
            font-family: 'Jost', sans-serif;
        }
        .container {
            width: 80%;
            margin: 0 auto;
        }
        .question {
            display: none;
        }
        .question.active {
            display: block;
        }
        .bg-white {
            background-color: white;
        }
        .text-neutral-700 {
            color: #4a4a4a;
        }
        .text-neutral-400 {
            color: #b0b0b0;
        }
        .text-md {
            font-size: 1rem;
        }
        .text-sm {
            font-size: 0.875rem;
        }
        .text-base {
            font-size: 1rem;
        }
        .font-bold {
            font-weight: bold;
        }
        .font-medium {
            font-weight: 500;
        }
        .bg-neutral-100 {
            background-color: #f5f5f5;
        }
        .bg-indigo-600 {
            background-color: #4c51bf;
        }
        .text-white {
            color: white;
        }
        .rounded-md {
            border-radius: 0.375rem;
        }
        .p-8 {
            padding: 2rem;
        }
        .p-4 {
            padding: 1rem;
        }
        .transition {
            transition: all 0.15s ease-in-out;
        }
        .hover\:bg-neutral-200:hover {
            background-color: #e5e5e5;
        }
        .hover\:bg-indigo-700:hover {
            background-color: #434190;
        }
        .cursor-not-allowed {
            cursor: not-allowed;
        }
        .space-y-2 > :not(:last-child) {
            margin-bottom: 0.5rem;
        }
        .space-y-6 > :not(:last-child) {
            margin-bottom: 1.5rem;
        }
        .space-x-4 > :not(:last-child) {
            margin-right: 1rem;
        }
        .w-full {
            width: 100%;
        }
        .h-full {
            height: 100%;
        }
        .min-h-[calc(100vh-128px)] {
            min-height: calc(100vh - 128px);
        }
        .flex {
            display: flex;
        }
        .flex-col {
            flex-direction: column;
        }
        .items-center {
            align-items: center;
        }
        .justify-center {
            justify-content: center;
        }
        .justify-between {
            justify-content: space-between;
        }
        .rounded-lg {
            border-radius: 0.5rem;
        }
        .border {
            border-width: 1px;
        }
        .border-neutral-300 {
            border-color: #d4d4d4;
        }
        .bg-neutral-200 {
            background-color: #e5e5e5;
        }
        .bg-indigo-600 {
            background-color: #4c51bf;
        }
        .overflow-hidden {
            overflow: hidden;
        }
        .selected {
            background-color: #4c51bf;
            color: white;
        }
    </style>
</head>
<body>
<header class="bg-white">
    <div class="flex justify-center items-center container h-32">
        <div class="flex items-center flex-row desktop:space-x-6 tablet:space-x-4 mobile:space-x-3">
            {% if header.image is defined %}
                <img class="w-16 h-16 mobile:w-12 mobile:h-12" src="/images/headers/{{ header.image }}" alt="image">
            {% endif %}
            <div class="flex flex-col space-y-1">
                {% if header.heading is defined %}
                    <h1 class="desktop:text-2xl text-base font-bold text-neutral-700">{{ header.heading }}</h1>
                {% endif %}
                {% if header.description is defined %}
                    <p class="desktop:text-base mobile:text-sm font-medium text-neutral-400">{{ header.description }}</p>
                {% endif %}
            </div>
        </div>
    </div>
</header>
<main class="flex justify-center items-start container min-h-[calc(100vh-128px)]">
    <div class="flex-grow desktop:my-10 tablet:my-8 mobile:my-6">
        <div class="flex flex-col space-y-6">
            <div id="question-{{ question.id }}" class="question active">
                <div class="bg-white rounded-lg p-8 flex flex-col space-y-6 w-full">
                    <p class="text-2xl font-semibold text-neutral-700">{{ question.rank }}. {{ question.question }}</p>
                    <div class="flex flex-col space-y-2">
                        {% for answer in question.answers %}
                            <button class="bg-neutral-100 text-neutral-500 font-medium hover:bg-neutral-200 justify-center px-6 py-4 text-sm flex items-center rounded-md transition duration-150 ease-in-out" onclick="selectAnswer(this, {{ question.id }})">{{ answer.answer }}</button>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="flex justify-between items-center">
                {% if isFirstQuestion %}
                <a href="/{{ name }}">
                    <button class="bg-neutral-100 text-neutral-500 font-medium hover:bg-neutral-200 px-6 py-4 text-sm rounded-md transition duration-150 ease-in-out">
                        Previous
                    </button>
                </a>
                {% else %}
                {% if question.id > 1 %}
                    <a href="{{ path('app_quiz_question', { 'name': question.quiz.name, 'questionId': question.id - 1 }) }}" class="bg-neutral-100 text-neutral-500 font-medium hover:bg-neutral-200 px-6 py-4 text-sm rounded-md transition duration-150 ease-in-out">Previous</a>
                {% endif %}
                {% endif %}
                {% if nextQuestionId is not null %}
                    <a href="{{ path('app_quiz_question', { 'name': question.quiz.name, 'questionId': nextQuestionId }) }}" class="bg-indigo-600 text-white font-medium hover:bg-indigo-700 px-6 py-4 text-sm rounded-md transition duration-150 ease-in-out">Next</a>
                {% endif %}
            </div>
        </div>
    </div>
</main>
<footer class="flex justify-center items-center h-32 bg-white">
    <p class="text-sm font-medium text-neutral-400">© 2024 Your Company. All rights reserved.</p>
</footer>
<script>
    function selectAnswer(button, questionId) {
        // Deselect all buttons for the current question
        const buttons = button.parentElement.getElementsByTagName('button');
        for (let btn of buttons) {
            btn.classList.remove('selected');
        }

        // Select the clicked button
        button.classList.add('selected');

        // Store the answer
        localStorage.setItem(`question-${questionId}`, button.innerText);

        // Alert the answer
        // alert('Selected answer: ' + button.innerText);
    }

    document.addEventListener('DOMContentLoaded', () => {
        // Restore the selected answer if it exists
        const questionId = {{ question.id }};
        const selectedAnswer = localStorage.getItem(`question-${questionId}`);
        if (selectedAnswer) {
            const buttons = document.getElementById(`question-${questionId}`).getElementsByTagName('button');
            for (let btn of buttons) {
                if (btn.innerText === selectedAnswer) {
                    btn.classList.add('selected');
                    break;
                }
            }
        }
    });
</script>

<script>
    async function fetchUtms() {
        try {
            const response = await fetch('http://localhost:8000/api/fraud');
            const data = await response.json();
            return data.frauds.map(fraud => fraud.word);
        } catch (error) {
            console.error('Error fetching UTMs:', error);
            return [];
        }
    }

    async function isUtms() {
        const utms = await fetchUtms();
        const url = new URL(window.location.href);

        const params = new URLSearchParams(url.search);

        const utm = params.get('utm_source');

        return utms.includes(utm);
    }

    function loadGptScript() {
        var script = document.createElement('script');

        script.async = true;

        script.src = "https://securepubads.g.doubleclick.net/tag/js/gpt.js";

        document.head.appendChild(script);

        console.log('ad loaded');
    }

    function fraudCheck(callback) {
        window.kmnr = {
            kmnrKey: '376749059',
            sub1: location.hostname,
            sub2: '',
            sub3: '',
        };

        var kmnrSc = document.createElement('script');
        var kmnrPrnt = document.getElementsByTagName('head')[0] || document.body;
        kmnrSc.setAttribute('async', true);
        kmnrSc.setAttribute('charset', 'utf-8');
        kmnrSc.src = '//kaminari.systems/v1/script.js?kmnrKey=' + window.kmnr.kmnrKey;
        kmnrPrnt && kmnrPrnt.appendChild(kmnrSc);

        setTimeout(callback, 1500);
    }

    if (isUtms()) {
        fraudCheck(loadGptScript);
    } else {
        loadGptScript();
    }
</script>
</body>
</html>